name: CTF
description: Capture The Flag Indexer
contracts:
  - name: CTF
    events:
      - event: WinnersChanged(address indexed newWinner)
      - event: RewardDistributed(address indexed winner, uint256 position, uint256 amount)

networks:
  - id: 8453
    start_block: 40802424
    contracts:
      - name: CTF
        address: 0x6c8ddc7a8a1945ac3ba1dd8b1e470e5faefefdf8
