# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 40848600
  contracts:
  - name: CTF
    address:
    - 0xa1fd5bF969ADa2b7F86Da87198ef2A275eFdca70
    handler: src/EventHandlers.ts
    events:
    - event: RewardDistributed(address indexed winner, uint256 position, uint256 amount)
    - event: WinnersChanged(address indexed newWinner)
unordered_multichain_mode: true
preload_handlers: true
