# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 40854276
  contracts:
  - name: CTF
    address:
    - 0x9d6c330dF06C3fe305135c7DA66A8B5e552CDD49
    handler: src/EventHandlers.ts
    events:
    - event: RewardDistributed(address indexed winner, uint256 position, uint256 amount)
    - event: WinnersChanged(address indexed newWinner)
unordered_multichain_mode: true
preload_handlers: true
